version: "3.8"
services:
  proxy:
    build: "./proxy"
    depends_on:
      - frontend
      - backend
    ports:
      - "8080:8080"
  frontend:
    image: wastingnotime/contacts-frontend:latest
    expose:
      - "80"
  backend:
    image: wastingnotime/contacts-backend:latest
    expose:
      - "8010"
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq_data:/data
volumes:
  mongodb_data:
  seq_data:
