version: "3.8"
services:
  proxy:
    build: "./proxy"
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
  frontend:
    image: wastingnotime/contacts-frontend:latest
    expose:
      - "80"
  backend:
    image: wastingnotime/contacts-backend:latest
    expose:
      - "8010"
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq_data:/data
volumes:
  seq_data:
